spring:
  profiles:
    active: mysql
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/imagebase
    username: imagebase
    password: ImageBase2023Run
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    password:
    timeout: 60000
  mail:
    host: smtp.gmail.com
    port: 587
    username: setusername
    password: setpassword
    auth: true
    starttls:
      enable: true



logging:
  pattern:
    console: "%clr(%d{HH:mm:ss.SSS}){faint} %clr(${LOG_LEVEL_PATTERN:%5p}) %clr(-){faint} %clr([%t]){faint} %clr(%-40logger{39}){cyan}[%line]%clr(:){faint} %m%n${LOG_EXCEPTION_CONVERSION_WORD:%wEx}"
  level:
    root: INFO